export const AUDIT_SCHEMA = [
    `create table if not exists security.audit_logs (\n  audit_id bigint generated by default as identity primary key,\n  created_at timestamptz not null default now(),\n  request_id text,\n  user_id bigint,\n  profile_id bigint,\n  action text not null,\n  object_name text,\n  method_name text,\n  tx integer,\n  meta jsonb\n);`,
    `create index if not exists ix_audit_logs_created_at on security.audit_logs(created_at desc);`,
    `create index if not exists ix_audit_logs_user_id on security.audit_logs(user_id);`,
    `create index if not exists ix_audit_logs_action on security.audit_logs(action);`,
]
