export function getAuthSchema(options: { authUsername: boolean }) {
    const base = [
        // Optional email
        `alter table security.users add column if not exists email text;`,
        `alter table security.users add column if not exists email_verified_at timestamptz;`,
        `create unique index if not exists uq_users_email on security.users(email) where email is not null;`,

        // Password Reset
        `create table if not exists security.password_resets (
  password_reset_id bigint generated by default as identity primary key,
  user_id bigint not null references security.users(user_id) on delete cascade,
  token_hash text not null,
  token_sent_to text,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  used_at timestamptz,
  request_ip inet,
  user_agent text,
  attempt_count integer not null default 0,
  meta jsonb
);`,
        `create unique index if not exists uq_password_resets_token_hash on security.password_resets(token_hash);`,
        `create index if not exists ix_password_resets_user_id on security.password_resets(user_id);`,
        `create index if not exists ix_password_resets_expires_at on security.password_resets(expires_at);`,

        // One Time Codes
        `create table if not exists security.one_time_codes (
  one_time_code_id bigint generated by default as identity primary key,
  user_id bigint not null references security.users(user_id) on delete cascade,
  purpose text not null,
  code_hash text not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  consumed_at timestamptz,
  attempt_count integer not null default 0,
  meta jsonb
);`,
        `create index if not exists ix_one_time_codes_user_purpose on security.one_time_codes(user_id, purpose, created_at desc);`,
        `create index if not exists ix_one_time_codes_expires_at on security.one_time_codes(expires_at);`,
    ]

    if (!options.authUsername) {
        base.push(`alter table security.users alter column username drop not null;`)
    }

    return base
}
