/**
 * Base Security Schema
 * Creates the core tables for authentication and authorization.
 */
export const BASE_SCHEMA = [
    // Schema
    `create schema if not exists security;`,

    // Profiles table
    `create table if not exists security.profiles (
        profile_id bigint generated by default as identity primary key,
        profile_name text
    );`,

    // Users table
    `create table if not exists security.users (
        user_id bigint generated by default as identity primary key,
        username text not null unique,
        password text not null,
        is_active boolean not null default true,
        created_at timestamptz not null default now(),
        updated_at timestamptz not null default now(),
        last_login_at timestamptz
    );`,

    // User-Profile mapping
    `create table if not exists security.user_profiles (
        user_id bigint not null references security.users(user_id) on delete cascade,
        profile_id bigint not null references security.profiles(profile_id) on delete cascade,
        primary key (user_id, profile_id)
    );`,

    // Objects (Business Objects)
    `create table if not exists security.objects (
        object_id bigint generated by default as identity primary key,
        object_name text not null unique
    );`,

    // Methods (Transactions)
    `create table if not exists security.methods (
        method_id bigint generated by default as identity primary key,
        object_id bigint not null references security.objects(object_id) on delete cascade,
        method_name text not null,
        tx integer not null,
        constraint uq_method_object unique (object_id, method_name),
        constraint uq_method_tx unique (tx),
        constraint ck_method_tx_positive check (tx > 0)
    );`,

    // Permission mapping
    `create table if not exists security.permission_methods (
        profile_id bigint not null references security.profiles(profile_id) on delete cascade,
        method_id bigint not null references security.methods(method_id) on delete cascade,
        primary key (profile_id, method_id)
    );`,

    // Indexes
    `create index if not exists ix_user_profiles_profile_id on security.user_profiles(profile_id);`,
    `create index if not exists ix_methods_object_id on security.methods(object_id);`,
    `create index if not exists ix_permission_methods_method_id on security.permission_methods(method_id);`,
]
