/**
 * Audit Schema
 * Tables for tracking user actions and system events.
 */
export const AUDIT_SCHEMA = [
    `create table if not exists security.audit_logs (
        audit_log_id bigint generated by default as identity primary key,
        user_id bigint references security.users(user_id),
        object_name text,
        method_name text,
        tx integer,
        action text,
        details jsonb,
        created_at timestamptz not null default now()
    );`,

    `create index if not exists ix_audit_logs_user_id on security.audit_logs(user_id);`,
    `create index if not exists ix_audit_logs_created_at on security.audit_logs(created_at);`,
]
